# Paths
data_root: "/home/phd/datasets/"

# Datasets
datasets:
  - "mvtec_ad"
  - "dagm_2007"
  - "ksdd2"

# Federation
num_clients: 8 # 13
num_rounds: 50
local_epochs: 5
batch_size: 32

# Model
latent_dim: 128
cvae_hidden: [512, 256, 128]
gcr_weight: 0.5
trust_weights: [0.333, 0.333, 0.333]  # alpha, beta, gamma

# DP
dp_afe:
  epsilon: 5.0
  delta: 1e-3
  max_grad_norm: 2.0
dp_cvae:
  epsilon: 1.0
  delta: 1e-5
  max_grad_norm: 1.0
  noise_multiplier: 1.2

# Downstream
downstream_model: "unet"  ####### or "linear"